services:

  api:
    build:
      context: .
      dockerfile: prompt/Dockerfile
    ports:
      - 9001:8000

  ui:
    build:
      context: ./chat-ui
      dockerfile: Dockerfile
    ports:
      - 91:80
    depends_on:
      - api
